<center> <font size="10" color="#de3831">
    <b> PROYECTO FINAL </b>
</font> </center>

<center> <font size="5" color="white"> Grupo 3 / Samuel Fernando Méndez Saldías 22033190 </font> </center>

In [3]:
pip install qrcode


  Created wheel for qrcode: filename=qrcode-7.3.1-py3-none-any.whl size=40385 sha256=0872a04b1da6b98e73219f8b57c2311638af2056d029d803db721a6cb158d80e
  Stored in directory: c:\users\feern\appdata\local\pip\cache\wheels\35\fd\04\2768886c56207acee0d6dc6b9bd5d06dac63a810f0c0a42516
Successfully built qrcode
Note: you may need to restart the kernel to use updated packages.


In [6]:
import qrcode as qr

In [10]:
git_samuel = qr.make("https://github.com/sfms97")

In [11]:
git_samuel.save('github_22033190.png')

In [13]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [14]:
import cv2

In [16]:
qr_img=cv2.imread('github_22033190.png')

In [17]:
type(qr_img)

numpy.ndarray

In [18]:
detector = cv2.QRCodeDetector()

In [21]:
text, matrix, val = detector.detectAndDecode(qr_img)

In [22]:
text

'https://github.com/sfms97'

In [24]:
matrix

array([[[ 40.     ,  40.     ],
        [288.99997,  40.     ],
        [288.99997, 288.99997],
        [ 40.     , 288.99997]]], dtype=float32)

In [35]:
pasaporte_cristian = cv2.imread("pasaporte_christian.png")

In [36]:
text2, matrix2, val2 = detector.detectAndDecode(pasaporte_cristian)

In [37]:
text2

'HC1:NCFOXN%TSMAHN-HXOCLGML-P8ZVHGJ-AH:TA1ROT$SD PL*IS2VF%GKG5/*E*71F/8X*G3M9JUPY0BZW4V/AY73CNN7J3J1H:43DAJBRNFG3CNBRI3CHG7KM0KLGJJ5C9-JE%7A6IA*$36IASD9YHILIIX2MELNKHKYIARGEX3E1.BLEE$JDM:C5H8QNL1FE1.B7I9 H9/.DV2MGDIR0MTDQVOCIL8-TIK*R3T3+7A.N88J4R$FBMA2 U6QS25P0QIRR97I2HOAAP9UY9VYCDEBD0HX2JR$4O1K8KES/F-1JZ.KELNZEG%12/9TL4T.B9 UP9C1-ZEN.HQCEFREGUA P1NV1K/U31AP8Q0OE+51QN1RNU.*U-51JFEKQU2:UWH9 UPRB8LTD1$AZWJYQ2%VLUHGG%5TW5A 6+O67N6F7E46WW%9Z4EM2PKAWMO9T.3NB1E7R0%K06N0%8/YM.QPMSD9IM28K/NS /K%TTVP5TPTT$CKTMS MKCHK+RO2W58ECQ568HX%A+YP8MAKL62QG'

In [38]:
val2

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0, 255, 255, ..., 255, 255,   0],
       [  0, 255,   0, ...,   0, 255,   0],
       ...,
       [  0, 255,   0, ...,   0, 255, 255],
       [  0, 255, 255, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0, 255]], dtype=uint8)

In [39]:
matrix2

array([[[  9.,   9.],
        [785.,   9.],
        [785., 787.],
        [  9., 787.]]], dtype=float32)